/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { QtiError } from "./qtierror.js";

/**
 * Internal server error response
 */
export type RemoveAssessmentItemInternalServerErrorData = {
  /**
   * Error type identifier
   */
  error: string;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * Sentry event ID for error tracking
   */
  eventId?: string | undefined;
  /**
   * Stack trace or additional error details
   */
  details: string;
};

/**
 * Internal server error response
 */
export class RemoveAssessmentItemInternalServerError extends QtiError {
  /**
   * Error type identifier
   */
  error: string;
  /**
   * Sentry event ID for error tracking
   */
  eventId?: string | undefined;
  /**
   * Stack trace or additional error details
   */
  details: string;

  /** The original data that was passed to this error instance. */
  data$: RemoveAssessmentItemInternalServerErrorData;

  constructor(
    err: RemoveAssessmentItemInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.eventId != null) this.eventId = err.eventId;
    this.details = err.details;

    this.name = "RemoveAssessmentItemInternalServerError";
  }
}

/**
 * Assessment test, test part, section, or item reference not found
 */
export type RemoveAssessmentItemNotFoundErrorData = {
  error: string;
};

/**
 * Assessment test, test part, section, or item reference not found
 */
export class RemoveAssessmentItemNotFoundError extends QtiError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: RemoveAssessmentItemNotFoundErrorData;

  constructor(
    err: RemoveAssessmentItemNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "RemoveAssessmentItemNotFoundError";
  }
}

/** @internal */
export const RemoveAssessmentItemInternalServerError$inboundSchema: z.ZodType<
  RemoveAssessmentItemInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
  message: z.string(),
  eventId: z.string().optional(),
  details: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new RemoveAssessmentItemInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type RemoveAssessmentItemInternalServerError$Outbound = {
  error: string;
  message: string;
  eventId?: string | undefined;
  details: string;
};

/** @internal */
export const RemoveAssessmentItemInternalServerError$outboundSchema: z.ZodType<
  RemoveAssessmentItemInternalServerError$Outbound,
  z.ZodTypeDef,
  RemoveAssessmentItemInternalServerError
> = z.instanceof(RemoveAssessmentItemInternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string(),
    message: z.string(),
    eventId: z.string().optional(),
    details: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RemoveAssessmentItemInternalServerError$ {
  /** @deprecated use `RemoveAssessmentItemInternalServerError$inboundSchema` instead. */
  export const inboundSchema =
    RemoveAssessmentItemInternalServerError$inboundSchema;
  /** @deprecated use `RemoveAssessmentItemInternalServerError$outboundSchema` instead. */
  export const outboundSchema =
    RemoveAssessmentItemInternalServerError$outboundSchema;
  /** @deprecated use `RemoveAssessmentItemInternalServerError$Outbound` instead. */
  export type Outbound = RemoveAssessmentItemInternalServerError$Outbound;
}

/** @internal */
export const RemoveAssessmentItemNotFoundError$inboundSchema: z.ZodType<
  RemoveAssessmentItemNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new RemoveAssessmentItemNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type RemoveAssessmentItemNotFoundError$Outbound = {
  error: string;
};

/** @internal */
export const RemoveAssessmentItemNotFoundError$outboundSchema: z.ZodType<
  RemoveAssessmentItemNotFoundError$Outbound,
  z.ZodTypeDef,
  RemoveAssessmentItemNotFoundError
> = z.instanceof(RemoveAssessmentItemNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RemoveAssessmentItemNotFoundError$ {
  /** @deprecated use `RemoveAssessmentItemNotFoundError$inboundSchema` instead. */
  export const inboundSchema = RemoveAssessmentItemNotFoundError$inboundSchema;
  /** @deprecated use `RemoveAssessmentItemNotFoundError$outboundSchema` instead. */
  export const outboundSchema =
    RemoveAssessmentItemNotFoundError$outboundSchema;
  /** @deprecated use `RemoveAssessmentItemNotFoundError$Outbound` instead. */
  export type Outbound = RemoveAssessmentItemNotFoundError$Outbound;
}
