// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// CreateAssessmentItemInternalServerError - Internal server error response
type CreateAssessmentItemInternalServerError struct {
	// Error type identifier
	Error_ string `json:"error"`
	// Human-readable error message
	Message string `json:"message"`
	// Sentry event ID for error tracking
	EventID *string `json:"eventId,omitempty"`
	// Stack trace or additional error details
	Details  string                  `json:"details"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &CreateAssessmentItemInternalServerError{}

func (e *CreateAssessmentItemInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateAssessmentItemConflictError - Assessment item with this identifier already exists
type CreateAssessmentItemConflictError struct {
	Error_   string                  `json:"error"`
	Details  *string                 `json:"details,omitempty"`
	Message  *string                 `json:"message,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &CreateAssessmentItemConflictError{}

func (e *CreateAssessmentItemConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// CreateAssessmentItemBadRequestError - Invalid request body or stimulus not found
type CreateAssessmentItemBadRequestError struct {
	Error_   string                  `json:"error"`
	Details  *string                 `json:"details,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &CreateAssessmentItemBadRequestError{}

func (e *CreateAssessmentItemBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
