// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// DeleteTestPartInternalServerError - Internal server error response
type DeleteTestPartInternalServerError struct {
	// Error type identifier
	Error_ string `json:"error"`
	// Human-readable error message
	Message string `json:"message"`
	// Sentry event ID for error tracking
	EventID *string `json:"eventId,omitempty"`
	// Stack trace or additional error details
	Details  string                  `json:"details"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DeleteTestPartInternalServerError{}

func (e *DeleteTestPartInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// DeleteTestPartNotFoundError - Assessment test or test part not found
type DeleteTestPartNotFoundError struct {
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &DeleteTestPartNotFoundError{}

func (e *DeleteTestPartNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
