// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// GetSectionInternalServerError - Internal server error response
type GetSectionInternalServerError struct {
	// Error type identifier
	Error_ string `json:"error"`
	// Human-readable error message
	Message string `json:"message"`
	// Sentry event ID for error tracking
	EventID *string `json:"eventId,omitempty"`
	// Stack trace or additional error details
	Details  string                  `json:"details"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetSectionInternalServerError{}

func (e *GetSectionInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetSectionNotFoundError - Assessment test, test part, or section not found
type GetSectionNotFoundError struct {
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetSectionNotFoundError{}

func (e *GetSectionNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// GetSectionBadRequestError - Missing required parameters
type GetSectionBadRequestError struct {
	Error_   string                  `json:"error"`
	Details  *string                 `json:"details,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetSectionBadRequestError{}

func (e *GetSectionBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
