// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// UpdateSectionNotImplementedError - XML format not supported
type UpdateSectionNotImplementedError struct {
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateSectionNotImplementedError{}

func (e *UpdateSectionNotImplementedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateSectionInternalServerError - Internal server error response
type UpdateSectionInternalServerError struct {
	// Error type identifier
	Error_ string `json:"error"`
	// Human-readable error message
	Message string `json:"message"`
	// Sentry event ID for error tracking
	EventID *string `json:"eventId,omitempty"`
	// Stack trace or additional error details
	Details  string                  `json:"details"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateSectionInternalServerError{}

func (e *UpdateSectionInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateSectionNotFoundError - Assessment test, test part, or section not found
type UpdateSectionNotFoundError struct {
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateSectionNotFoundError{}

func (e *UpdateSectionNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateSectionBadRequestError - Missing required parameters or invalid section data
type UpdateSectionBadRequestError struct {
	Error_   string                  `json:"error"`
	Details  *string                 `json:"details,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateSectionBadRequestError{}

func (e *UpdateSectionBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
