// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// UpdateAssessmentTestRawInternalServerError - Internal server error response
type UpdateAssessmentTestRawInternalServerError struct {
	// Error type identifier
	Error_ string `json:"error"`
	// Human-readable error message
	Message string `json:"message"`
	// Sentry event ID for error tracking
	EventID *string `json:"eventId,omitempty"`
	// Stack trace or additional error details
	Details  string                  `json:"details"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateAssessmentTestRawInternalServerError{}

func (e *UpdateAssessmentTestRawInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateAssessmentTestRawNotFoundError - Assessment test not found
type UpdateAssessmentTestRawNotFoundError struct {
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateAssessmentTestRawNotFoundError{}

func (e *UpdateAssessmentTestRawNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
