// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// UpdateStimulusInternalServerError - Internal server error response
type UpdateStimulusInternalServerError struct {
	// Error type identifier
	Error_ string `json:"error"`
	// Human-readable error message
	Message string `json:"message"`
	// Sentry event ID for error tracking
	EventID *string `json:"eventId,omitempty"`
	// Stack trace or additional error details
	Details  string                  `json:"details"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateStimulusInternalServerError{}

func (e *UpdateStimulusInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateStimulusNotFoundError - Stimulus not found or Failed to update Stimulus
type UpdateStimulusNotFoundError struct {
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateStimulusNotFoundError{}

func (e *UpdateStimulusNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateStimulusBadRequestError - Invalid stimulus data
type UpdateStimulusBadRequestError struct {
	Error_   string                  `json:"error"`
	Details  *string                 `json:"details,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateStimulusBadRequestError{}

func (e *UpdateStimulusBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
