// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// UpdateAssessmentItemInternalServerError - Internal server error response
type UpdateAssessmentItemInternalServerError struct {
	// Error type identifier
	Error_ string `json:"error"`
	// Human-readable error message
	Message string `json:"message"`
	// Sentry event ID for error tracking
	EventID *string `json:"eventId,omitempty"`
	// Stack trace or additional error details
	Details  string                  `json:"details"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateAssessmentItemInternalServerError{}

func (e *UpdateAssessmentItemInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateAssessmentItemNotFoundError - Item not found
type UpdateAssessmentItemNotFoundError struct {
	Error_   string                  `json:"error"`
	Details  *string                 `json:"details,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateAssessmentItemNotFoundError{}

func (e *UpdateAssessmentItemNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// UpdateAssessmentItemBadRequestError - Invalid request body or stimulus not found
type UpdateAssessmentItemBadRequestError struct {
	Error_   string                  `json:"error"`
	Details  *string                 `json:"details,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &UpdateAssessmentItemBadRequestError{}

func (e *UpdateAssessmentItemBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
