/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assessmentTestManagementUpdateAssessmentTest } from "../../funcs/assessmentTestManagementUpdateAssessmentTest.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateAssessmentTestRequest$inboundSchema,
};

export const tool$assessmentTestManagementUpdateAssessmentTest: ToolDefinition<
  typeof args
> = {
  name: "assessment-test-management-update-assessment-test",
  description: `Update an entire assessment test

Update an assessment test by replacing its complete structure. This operation updates the entire assessment test including its test parts, sections, and item references. Supports both JSON and XML formats. The updated XML structure is automatically regenerated.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await assessmentTestManagementUpdateAssessmentTest(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
