/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assessmentItemManagementUpdateAssessmentItem } from "../../funcs/assessmentItemManagementUpdateAssessmentItem.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateAssessmentItemRequest$inboundSchema,
};

export const tool$assessmentItemManagementUpdateAssessmentItem: ToolDefinition<
  typeof args
> = {
  name: "assessment-item-management-update-assessment-item",
  description: `Update an assessment item's content and configuration

Update an assessment item including its question content, interactions, response processing, and scoring logic. This operation regenerates the QTI XML structure and validates all content. Assessment tests that reference this item will automatically use the updated version.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await assessmentItemManagementUpdateAssessmentItem(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
