/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assessmentItemManagementGetAssessmentItem } from "../../funcs/assessmentItemManagementGetAssessmentItem.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAssessmentItemRequest$inboundSchema,
};

export const tool$assessmentItemManagementGetAssessmentItem: ToolDefinition<
  typeof args
> = {
  name: "assessment-item-management-get-assessment-item",
  description: `Get an assessment item with complete question content

Retrieve a specific assessment item including its question content, answer choices, interaction types, response processing rules, and scoring logic. Assessment items are the fundamental units of assessment content that can be referenced by test sections. Supports both JSON and XML response formats based on the Content-Type header.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await assessmentItemManagementGetAssessmentItem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
