/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testPartManagementGetTestPart } from "../../funcs/testPartManagementGetTestPart.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetTestPartRequest$inboundSchema,
};

export const tool$testPartManagementGetTestPart: ToolDefinition<typeof args> = {
  name: "test-part-management-get-test-part",
  description: `Get a specific test part with all its sections

Retrieve a test part by identifier including all its sections and their assessment item references. Test parts define navigation and submission behaviors for groups of sections. Supports both JSON and XML response formats.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await testPartManagementGetTestPart(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
