/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { QtiCore } from "../core.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { QtiError } from "../models/errors/qtierror.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Create a new assessment test
 *
 * @remarks
 * Create a new assessment test. Supports both JSON and XML formats.
 */
export function assessmentTestManagementCreateAssessmentTestRaw(
  client: QtiCore,
  request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.CreateAssessmentTestRawResponse,
    | errors.CreateAssessmentTestRawBadRequestError
    | errors.CreateAssessmentTestRawConflictError
    | errors.CreateAssessmentTestRawInternalServerError
    | QtiError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: QtiCore,
  request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.CreateAssessmentTestRawResponse,
      | errors.CreateAssessmentTestRawBadRequestError
      | errors.CreateAssessmentTestRawConflictError
      | errors.CreateAssessmentTestRawInternalServerError
      | QtiError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      z.union([
        z.instanceof(ReadableStream<Uint8Array>),
        z.instanceof(Blob),
        z.instanceof(ArrayBuffer),
        z.instanceof(Uint8Array),
      ]).parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = payload;

  const path = pathToFunc("/assessment-tests")();

  const headers = new Headers(compactMap({
    "Content-Type": "application/xml",
    Accept: "application/json",
  }));

  const securityInput = await extractSecurity(client._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "createAssessmentTest_raw",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.security,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["400", "409", "4XX", "500", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    operations.CreateAssessmentTestRawResponse,
    | errors.CreateAssessmentTestRawBadRequestError
    | errors.CreateAssessmentTestRawConflictError
    | errors.CreateAssessmentTestRawInternalServerError
    | QtiError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(201, operations.CreateAssessmentTestRawResponse$inboundSchema),
    M.jsonErr(400, errors.CreateAssessmentTestRawBadRequestError$inboundSchema),
    M.jsonErr(409, errors.CreateAssessmentTestRawConflictError$inboundSchema),
    M.jsonErr(
      500,
      errors.CreateAssessmentTestRawInternalServerError$inboundSchema,
    ),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
