/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { QtiCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$assessmentItemManagementCreateAssessmentItem } from "./tools/assessmentItemManagementCreateAssessmentItem.js";
import { tool$assessmentItemManagementDeleteAssessmentItem } from "./tools/assessmentItemManagementDeleteAssessmentItem.js";
import { tool$assessmentItemManagementGetAssessmentItem } from "./tools/assessmentItemManagementGetAssessmentItem.js";
import { tool$assessmentItemManagementSearchAssessmentItems } from "./tools/assessmentItemManagementSearchAssessmentItems.js";
import { tool$assessmentItemManagementUpdateAssessmentItem } from "./tools/assessmentItemManagementUpdateAssessmentItem.js";
import { tool$assessmentTestManagementCreateAssessmentTest } from "./tools/assessmentTestManagementCreateAssessmentTest.js";
import { tool$assessmentTestManagementCreateAssessmentTestRaw } from "./tools/assessmentTestManagementCreateAssessmentTestRaw.js";
import { tool$assessmentTestManagementDeleteAssessmentTest } from "./tools/assessmentTestManagementDeleteAssessmentTest.js";
import { tool$assessmentTestManagementGetAllQuestions } from "./tools/assessmentTestManagementGetAllQuestions.js";
import { tool$assessmentTestManagementGetAssessmentTest } from "./tools/assessmentTestManagementGetAssessmentTest.js";
import { tool$assessmentTestManagementSearchAssessmentTests } from "./tools/assessmentTestManagementSearchAssessmentTests.js";
import { tool$assessmentTestManagementUpdateAssessmentTest } from "./tools/assessmentTestManagementUpdateAssessmentTest.js";
import { tool$assessmentTestManagementUpdateAssessmentTestMetadata } from "./tools/assessmentTestManagementUpdateAssessmentTestMetadata.js";
import { tool$assessmentTestManagementUpdateAssessmentTestRaw } from "./tools/assessmentTestManagementUpdateAssessmentTestRaw.js";
import { tool$sectionManagementAddAssessmentItem } from "./tools/sectionManagementAddAssessmentItem.js";
import { tool$sectionManagementCreateSection } from "./tools/sectionManagementCreateSection.js";
import { tool$sectionManagementDeleteSection } from "./tools/sectionManagementDeleteSection.js";
import { tool$sectionManagementGetSection } from "./tools/sectionManagementGetSection.js";
import { tool$sectionManagementRemoveAssessmentItem } from "./tools/sectionManagementRemoveAssessmentItem.js";
import { tool$sectionManagementSearchSections } from "./tools/sectionManagementSearchSections.js";
import { tool$sectionManagementUpdateAssessmentItemOrder } from "./tools/sectionManagementUpdateAssessmentItemOrder.js";
import { tool$sectionManagementUpdateSection } from "./tools/sectionManagementUpdateSection.js";
import { tool$stimulusManagementCreateStimulus } from "./tools/stimulusManagementCreateStimulus.js";
import { tool$stimulusManagementDeleteStimulus } from "./tools/stimulusManagementDeleteStimulus.js";
import { tool$stimulusManagementGetStimulus } from "./tools/stimulusManagementGetStimulus.js";
import { tool$stimulusManagementSearchStimuli } from "./tools/stimulusManagementSearchStimuli.js";
import { tool$stimulusManagementUpdateStimulus } from "./tools/stimulusManagementUpdateStimulus.js";
import { tool$testPartManagementCreateTestPart } from "./tools/testPartManagementCreateTestPart.js";
import { tool$testPartManagementDeleteTestPart } from "./tools/testPartManagementDeleteTestPart.js";
import { tool$testPartManagementGetTestPart } from "./tools/testPartManagementGetTestPart.js";
import { tool$testPartManagementSearchTestParts } from "./tools/testPartManagementSearchTestParts.js";
import { tool$testPartManagementUpdateTestPart } from "./tools/testPartManagementUpdateTestPart.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Qti",
    version: "0.0.1",
  });

  const client = new QtiCore({
    security: deps.security,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$stimulusManagementSearchStimuli);
  tool(tool$stimulusManagementCreateStimulus);
  tool(tool$stimulusManagementGetStimulus);
  tool(tool$stimulusManagementUpdateStimulus);
  tool(tool$stimulusManagementDeleteStimulus);
  tool(tool$assessmentItemManagementSearchAssessmentItems);
  tool(tool$assessmentItemManagementCreateAssessmentItem);
  tool(tool$assessmentItemManagementGetAssessmentItem);
  tool(tool$assessmentItemManagementUpdateAssessmentItem);
  tool(tool$assessmentItemManagementDeleteAssessmentItem);
  tool(tool$assessmentTestManagementSearchAssessmentTests);
  tool(tool$assessmentTestManagementCreateAssessmentTest);
  tool(tool$assessmentTestManagementCreateAssessmentTestRaw);
  tool(tool$assessmentTestManagementGetAssessmentTest);
  tool(tool$assessmentTestManagementUpdateAssessmentTest);
  tool(tool$assessmentTestManagementUpdateAssessmentTestRaw);
  tool(tool$assessmentTestManagementDeleteAssessmentTest);
  tool(tool$assessmentTestManagementGetAllQuestions);
  tool(tool$assessmentTestManagementUpdateAssessmentTestMetadata);
  tool(tool$testPartManagementSearchTestParts);
  tool(tool$testPartManagementCreateTestPart);
  tool(tool$testPartManagementGetTestPart);
  tool(tool$testPartManagementUpdateTestPart);
  tool(tool$testPartManagementDeleteTestPart);
  tool(tool$sectionManagementSearchSections);
  tool(tool$sectionManagementCreateSection);
  tool(tool$sectionManagementGetSection);
  tool(tool$sectionManagementUpdateSection);
  tool(tool$sectionManagementDeleteSection);
  tool(tool$sectionManagementAddAssessmentItem);
  tool(tool$sectionManagementRemoveAssessmentItem);
  tool(tool$sectionManagementUpdateAssessmentItemOrder);

  return server;
}
