// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
	"time"
)

type CreateStimulusCatalogInfo struct {
	// Catalog entry identifier (must be valid XML NCName). The unique identifier used to locate the catalog from a data-catalog-idref.
	ID string `json:"id"`
	// This attribute names either pre-defined supports or a custom-named support. The named support will indicate for whom the dormant content is intended. Use only one card for any particular named support in a catalog
	Support string `json:"support"`
	// A data structure within a catalog which contains dormant HTML content or a resource reference for a specific support/feature. A card may also contain multiple CardEntry containers. For example, you might have multiple CardEntry nodes for different language versions of a particular support.
	Content string `json:"content"`
}

func (o *CreateStimulusCatalogInfo) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateStimulusCatalogInfo) GetSupport() string {
	if o == nil {
		return ""
	}
	return o.Support
}

func (o *CreateStimulusCatalogInfo) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}

// CreateStimulusStylesheet - The set of external style sheets that are associated with the Stimulus. The order of definition is significant.
type CreateStimulusStylesheet struct {
	// The identifier or location of the external stylesheet.
	Href string `json:"href"`
	// The type of the external stylesheet.
	Type string `json:"type"`
}

func (o *CreateStimulusStylesheet) GetHref() string {
	if o == nil {
		return ""
	}
	return o.Href
}

func (o *CreateStimulusStylesheet) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

type CreateStimulusAttributes struct {
	Xmlns             string `json:"xmlns"`
	XmlnsXsi          string `json:"xmlns:xsi"`
	XsiSchemaLocation string `json:"xsi:schemaLocation"`
	Identifier        string `json:"identifier"`
	XMLLang           string `json:"xml:lang"`
	Title             string `json:"title"`
}

func (o *CreateStimulusAttributes) GetXmlns() string {
	if o == nil {
		return ""
	}
	return o.Xmlns
}

func (o *CreateStimulusAttributes) GetXmlnsXsi() string {
	if o == nil {
		return ""
	}
	return o.XmlnsXsi
}

func (o *CreateStimulusAttributes) GetXsiSchemaLocation() string {
	if o == nil {
		return ""
	}
	return o.XsiSchemaLocation
}

func (o *CreateStimulusAttributes) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *CreateStimulusAttributes) GetXMLLang() string {
	if o == nil {
		return ""
	}
	return o.XMLLang
}

func (o *CreateStimulusAttributes) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

type CreateStimulusQtiStylesheetAttributes struct {
	Href string `json:"href"`
	Type string `json:"type"`
}

func (o *CreateStimulusQtiStylesheetAttributes) GetHref() string {
	if o == nil {
		return ""
	}
	return o.Href
}

func (o *CreateStimulusQtiStylesheetAttributes) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

type CreateStimulusQtiStylesheet struct {
	Attributes CreateStimulusQtiStylesheetAttributes `json:"_attributes"`
}

func (o *CreateStimulusQtiStylesheet) GetAttributes() CreateStimulusQtiStylesheetAttributes {
	if o == nil {
		return CreateStimulusQtiStylesheetAttributes{}
	}
	return o.Attributes
}

type CreateStimulusQtiCatalogAttributes struct {
	ID string `json:"id"`
}

func (o *CreateStimulusQtiCatalogAttributes) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type CreateStimulusQtiCardAttributes struct {
	Support string `json:"support"`
}

func (o *CreateStimulusQtiCardAttributes) GetSupport() string {
	if o == nil {
		return ""
	}
	return o.Support
}

type CreateStimulusQtiCard struct {
	Attributes     CreateStimulusQtiCardAttributes `json:"_attributes"`
	QtiHTMLContent map[string]any                  `json:"qti-html-content"`
}

func (o *CreateStimulusQtiCard) GetAttributes() CreateStimulusQtiCardAttributes {
	if o == nil {
		return CreateStimulusQtiCardAttributes{}
	}
	return o.Attributes
}

func (o *CreateStimulusQtiCard) GetQtiHTMLContent() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.QtiHTMLContent
}

type CreateStimulusQtiCatalog struct {
	Attributes CreateStimulusQtiCatalogAttributes `json:"_attributes"`
	QtiCard    CreateStimulusQtiCard              `json:"qti-card"`
}

func (o *CreateStimulusQtiCatalog) GetAttributes() CreateStimulusQtiCatalogAttributes {
	if o == nil {
		return CreateStimulusQtiCatalogAttributes{}
	}
	return o.Attributes
}

func (o *CreateStimulusQtiCatalog) GetQtiCard() CreateStimulusQtiCard {
	if o == nil {
		return CreateStimulusQtiCard{}
	}
	return o.QtiCard
}

type CreateStimulusQtiCatalogInfo struct {
	QtiCatalog CreateStimulusQtiCatalog `json:"qti-catalog"`
}

func (o *CreateStimulusQtiCatalogInfo) GetQtiCatalog() CreateStimulusQtiCatalog {
	if o == nil {
		return CreateStimulusQtiCatalog{}
	}
	return o.QtiCatalog
}

type CreateStimulusQtiAssessmentStimulus struct {
	Attributes      CreateStimulusAttributes      `json:"_attributes"`
	QtiStimulusBody map[string]any                `json:"qti-stimulus-body"`
	QtiStylesheet   *CreateStimulusQtiStylesheet  `json:"qti-stylesheet,omitempty"`
	QtiCatalogInfo  *CreateStimulusQtiCatalogInfo `json:"qti-catalog-info,omitempty"`
}

func (o *CreateStimulusQtiAssessmentStimulus) GetAttributes() CreateStimulusAttributes {
	if o == nil {
		return CreateStimulusAttributes{}
	}
	return o.Attributes
}

func (o *CreateStimulusQtiAssessmentStimulus) GetQtiStimulusBody() map[string]any {
	if o == nil {
		return map[string]any{}
	}
	return o.QtiStimulusBody
}

func (o *CreateStimulusQtiAssessmentStimulus) GetQtiStylesheet() *CreateStimulusQtiStylesheet {
	if o == nil {
		return nil
	}
	return o.QtiStylesheet
}

func (o *CreateStimulusQtiAssessmentStimulus) GetQtiCatalogInfo() *CreateStimulusQtiCatalogInfo {
	if o == nil {
		return nil
	}
	return o.QtiCatalogInfo
}

// CreateStimulusContent - Parsed XML content generated by the service provider. For production use, rawXml is recommended over this parsed structure.
type CreateStimulusContent struct {
	QtiAssessmentStimulus CreateStimulusQtiAssessmentStimulus `json:"qti-assessment-stimulus"`
}

func (o *CreateStimulusContent) GetQtiAssessmentStimulus() CreateStimulusQtiAssessmentStimulus {
	if o == nil {
		return CreateStimulusQtiAssessmentStimulus{}
	}
	return o.QtiAssessmentStimulus
}

// CreateStimulusResponseBody - Complete stimulus data structure returned from the database including parsed content and metadata
type CreateStimulusResponseBody struct {
	// MongoDB document ID generated by the database when a new entity is added to a collection on the service provider.
	ID string `json:"_id"`
	// Unique identifier for the entity on the service provider.
	Identifier string `json:"identifier"`
	// Human-readable title of the entity on the service provider.
	Title string `json:"title"`
	// Array of catalog cards.
	CatalogInfo []CreateStimulusCatalogInfo `json:"catalogInfo"`
	// A human readable label that can be used to describe the Stimulus.
	Label *string `json:"label,omitempty"`
	// The default language for the Stimulus.
	Language *string `default:"en" json:"language"`
	// The set of external style sheets that are associated with the Stimulus. The order of definition is significant.
	Stylesheet *CreateStimulusStylesheet `json:"stylesheet,omitempty"`
	// The tool name characteristic allows the tool creating the stimulus to identify itself. Other processing systems may use this information to interpret the content of application specific data, such as labels on the elements of the stimulus's stimulus body.
	ToolName *string `json:"toolName,omitempty"`
	// The tool version characteristic allows the tool creating the item to identify its version. This value must only be interpreted in the context of the tool-name.
	ToolVersion *string `json:"toolVersion,omitempty"`
	// Additional custom metadata for extending entity properties beyond standard specification for QTI entities.
	Metadata map[string]any `json:"metadata,omitempty"`
	// Raw XML representation of the entity, automatically generated from the JSON or XML sent when creating entities on the service provider. The rawxml field will contain all content sent when creating the entity on the service provider. This field is stable and should be used when working within this QTI API.
	RawXML string `json:"rawXml"`
	// Parsed XML content generated by the service provider. For production use, rawXml is recommended over this parsed structure.
	Content CreateStimulusContent `json:"content"`
	// ISO 8601 timestamp when the entity was created
	CreatedAt time.Time `json:"createdAt"`
	// ISO 8601 timestamp when the entity was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	// MongoDB version key for optimistic concurrency control
	V *float64 `json:"__v,omitempty"`
}

func (c CreateStimulusResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateStimulusResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateStimulusResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateStimulusResponseBody) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *CreateStimulusResponseBody) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *CreateStimulusResponseBody) GetCatalogInfo() []CreateStimulusCatalogInfo {
	if o == nil {
		return []CreateStimulusCatalogInfo{}
	}
	return o.CatalogInfo
}

func (o *CreateStimulusResponseBody) GetLabel() *string {
	if o == nil {
		return nil
	}
	return o.Label
}

func (o *CreateStimulusResponseBody) GetLanguage() *string {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *CreateStimulusResponseBody) GetStylesheet() *CreateStimulusStylesheet {
	if o == nil {
		return nil
	}
	return o.Stylesheet
}

func (o *CreateStimulusResponseBody) GetToolName() *string {
	if o == nil {
		return nil
	}
	return o.ToolName
}

func (o *CreateStimulusResponseBody) GetToolVersion() *string {
	if o == nil {
		return nil
	}
	return o.ToolVersion
}

func (o *CreateStimulusResponseBody) GetMetadata() map[string]any {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *CreateStimulusResponseBody) GetRawXML() string {
	if o == nil {
		return ""
	}
	return o.RawXML
}

func (o *CreateStimulusResponseBody) GetContent() CreateStimulusContent {
	if o == nil {
		return CreateStimulusContent{}
	}
	return o.Content
}

func (o *CreateStimulusResponseBody) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *CreateStimulusResponseBody) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *CreateStimulusResponseBody) GetV() *float64 {
	if o == nil {
		return nil
	}
	return o.V
}

type CreateStimulusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Stimulus created successfully
	Object *CreateStimulusResponseBody
}

func (o *CreateStimulusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateStimulusResponse) GetObject() *CreateStimulusResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
