// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type RemoveAssessmentItemRequest struct {
	// The unique identifier of the root assessment test
	AssessmentTestIdentifier string `pathParam:"style=simple,explode=false,name=assessmentTestIdentifier"`
	// The unique identifier of the parent test part
	TestPartIdentifier string `pathParam:"style=simple,explode=false,name=testPartIdentifier"`
	// The unique identifier of the target section
	Identifier string `pathParam:"style=simple,explode=false,name=identifier"`
	// The unique identifier of the assessment item reference to remove from the section
	ItemIdentifier string `pathParam:"style=simple,explode=false,name=itemIdentifier"`
}

func (o *RemoveAssessmentItemRequest) GetAssessmentTestIdentifier() string {
	if o == nil {
		return ""
	}
	return o.AssessmentTestIdentifier
}

func (o *RemoveAssessmentItemRequest) GetTestPartIdentifier() string {
	if o == nil {
		return ""
	}
	return o.TestPartIdentifier
}

func (o *RemoveAssessmentItemRequest) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *RemoveAssessmentItemRequest) GetItemIdentifier() string {
	if o == nil {
		return ""
	}
	return o.ItemIdentifier
}

type RemoveAssessmentItemResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *RemoveAssessmentItemResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
