// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type UpdateSectionRequest struct {
	// Root assessment test identifier
	AssessmentTestIdentifier string `pathParam:"style=simple,explode=false,name=assessmentTestIdentifier"`
	// Parent test part identifier
	TestPartIdentifier string `pathParam:"style=simple,explode=false,name=testPartIdentifier"`
	// Section identifier
	Identifier string `pathParam:"style=simple,explode=false,name=identifier"`
	// The section to update
	Section components.Section `request:"mediaType=application/json"`
}

func (o *UpdateSectionRequest) GetAssessmentTestIdentifier() string {
	if o == nil {
		return ""
	}
	return o.AssessmentTestIdentifier
}

func (o *UpdateSectionRequest) GetTestPartIdentifier() string {
	if o == nil {
		return ""
	}
	return o.TestPartIdentifier
}

func (o *UpdateSectionRequest) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *UpdateSectionRequest) GetSection() components.Section {
	if o == nil {
		return components.Section{}
	}
	return o.Section
}

// UpdateSectionQtiAssessmentItemRef - Assessment item reference schema for linking assessment items to sections
type UpdateSectionQtiAssessmentItemRef struct {
	// Unique identifier for the entity on the service provider.
	Identifier string `json:"identifier"`
	// URI reference to the assessment item resource location on the service provider
	Href *string `json:"href,omitempty"`
}

func (o *UpdateSectionQtiAssessmentItemRef) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *UpdateSectionQtiAssessmentItemRef) GetHref() *string {
	if o == nil {
		return nil
	}
	return o.Href
}

// UpdateSectionResponseBody - Complete assessment section data with all referenced items. Represents a section containing learning content within a test part.
type UpdateSectionResponseBody struct {
	// MongoDB document ID generated by the database when a new entity is added to a collection on the service provider.
	ID string `json:"_id"`
	// Unique identifier for the entity on the service provider.
	Identifier string `json:"identifier"`
	// Human-readable title of the entity on the service provider.
	Title string `json:"title"`
	// Determines whether the assessment section is visible to candidates during test delivery. Sections are visible by default unless explicitly hidden for specific assessment conditions.
	Visible *bool `default:"true" json:"visible"`
	// If a child element is required it must appear (at least once) in the selection.
	Required *bool `default:"true" json:"required"`
	// If a child element is fixed it must never be shuffled. When used in combination with a selection rule fixed elements do not have their position fixed until after selection has taken place.
	Fixed *bool `default:"false" json:"fixed"`
	// Defines the sequential order of this item within its parent section. Must be a positive integer that determines presentation order to candidates.
	Sequence *int64 `json:"sequence,omitempty"`
	// Collection of assessment items that are referenced within this section.
	QtiAssessmentItemRef []UpdateSectionQtiAssessmentItemRef `json:"qti-assessment-item-ref,omitempty"`
}

func (u UpdateSectionResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateSectionResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *UpdateSectionResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateSectionResponseBody) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *UpdateSectionResponseBody) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *UpdateSectionResponseBody) GetVisible() *bool {
	if o == nil {
		return nil
	}
	return o.Visible
}

func (o *UpdateSectionResponseBody) GetRequired() *bool {
	if o == nil {
		return nil
	}
	return o.Required
}

func (o *UpdateSectionResponseBody) GetFixed() *bool {
	if o == nil {
		return nil
	}
	return o.Fixed
}

func (o *UpdateSectionResponseBody) GetSequence() *int64 {
	if o == nil {
		return nil
	}
	return o.Sequence
}

func (o *UpdateSectionResponseBody) GetQtiAssessmentItemRef() []UpdateSectionQtiAssessmentItemRef {
	if o == nil {
		return nil
	}
	return o.QtiAssessmentItemRef
}

type UpdateSectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Section updated successfully
	Object *UpdateSectionResponseBody
}

func (o *UpdateSectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateSectionResponse) GetObject() *UpdateSectionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
