/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteAssessmentTestRequest = {
  /**
   * The identifier of the assessment test to delete
   */
  identifier: string;
};

/** @internal */
export const DeleteAssessmentTestRequest$inboundSchema: z.ZodType<
  DeleteAssessmentTestRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  identifier: z.string(),
});

/** @internal */
export type DeleteAssessmentTestRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const DeleteAssessmentTestRequest$outboundSchema: z.ZodType<
  DeleteAssessmentTestRequest$Outbound,
  z.ZodTypeDef,
  DeleteAssessmentTestRequest
> = z.object({
  identifier: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAssessmentTestRequest$ {
  /** @deprecated use `DeleteAssessmentTestRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteAssessmentTestRequest$inboundSchema;
  /** @deprecated use `DeleteAssessmentTestRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteAssessmentTestRequest$outboundSchema;
  /** @deprecated use `DeleteAssessmentTestRequest$Outbound` instead. */
  export type Outbound = DeleteAssessmentTestRequest$Outbound;
}

export function deleteAssessmentTestRequestToJSON(
  deleteAssessmentTestRequest: DeleteAssessmentTestRequest,
): string {
  return JSON.stringify(
    DeleteAssessmentTestRequest$outboundSchema.parse(
      deleteAssessmentTestRequest,
    ),
  );
}

export function deleteAssessmentTestRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAssessmentTestRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAssessmentTestRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAssessmentTestRequest' from JSON`,
  );
}
