/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteStimulusRequest = {
  /**
   * Stimulus identifier
   */
  identifier: string;
};

/** @internal */
export const DeleteStimulusRequest$inboundSchema: z.ZodType<
  DeleteStimulusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  identifier: z.string(),
});

/** @internal */
export type DeleteStimulusRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const DeleteStimulusRequest$outboundSchema: z.ZodType<
  DeleteStimulusRequest$Outbound,
  z.ZodTypeDef,
  DeleteStimulusRequest
> = z.object({
  identifier: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteStimulusRequest$ {
  /** @deprecated use `DeleteStimulusRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteStimulusRequest$inboundSchema;
  /** @deprecated use `DeleteStimulusRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteStimulusRequest$outboundSchema;
  /** @deprecated use `DeleteStimulusRequest$Outbound` instead. */
  export type Outbound = DeleteStimulusRequest$Outbound;
}

export function deleteStimulusRequestToJSON(
  deleteStimulusRequest: DeleteStimulusRequest,
): string {
  return JSON.stringify(
    DeleteStimulusRequest$outboundSchema.parse(deleteStimulusRequest),
  );
}

export function deleteStimulusRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteStimulusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteStimulusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteStimulusRequest' from JSON`,
  );
}
