/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteAssessmentItemRequest = {
  /**
   * The unique identifier of the assessment item to delete
   */
  identifier: string;
};

/** @internal */
export const DeleteAssessmentItemRequest$inboundSchema: z.ZodType<
  DeleteAssessmentItemRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  identifier: z.string(),
});

/** @internal */
export type DeleteAssessmentItemRequest$Outbound = {
  identifier: string;
};

/** @internal */
export const DeleteAssessmentItemRequest$outboundSchema: z.ZodType<
  DeleteAssessmentItemRequest$Outbound,
  z.ZodTypeDef,
  DeleteAssessmentItemRequest
> = z.object({
  identifier: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAssessmentItemRequest$ {
  /** @deprecated use `DeleteAssessmentItemRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteAssessmentItemRequest$inboundSchema;
  /** @deprecated use `DeleteAssessmentItemRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteAssessmentItemRequest$outboundSchema;
  /** @deprecated use `DeleteAssessmentItemRequest$Outbound` instead. */
  export type Outbound = DeleteAssessmentItemRequest$Outbound;
}

export function deleteAssessmentItemRequestToJSON(
  deleteAssessmentItemRequest: DeleteAssessmentItemRequest,
): string {
  return JSON.stringify(
    DeleteAssessmentItemRequest$outboundSchema.parse(
      deleteAssessmentItemRequest,
    ),
  );
}

export function deleteAssessmentItemRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteAssessmentItemRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteAssessmentItemRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteAssessmentItemRequest' from JSON`,
  );
}
