// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type SchemeOAuth2 struct {
	ClientID     string `security:"name=clientID"`
	ClientSecret string `security:"name=clientSecret"`
	TokenURL     string `default:"https://alpha-auth-production-idp.auth.us-west-2.amazoncognito.com/oauth2/token"`
}

func (s SchemeOAuth2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemeOAuth2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SchemeOAuth2) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *SchemeOAuth2) GetClientSecret() string {
	if o == nil {
		return ""
	}
	return o.ClientSecret
}

func (o *SchemeOAuth2) GetTokenURL() string {
	if o == nil {
		return ""
	}
	return o.TokenURL
}
